CREATE TABLE users (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR2(255 CHAR) NOT NULL,
    password VARCHAR2(255 CHAR) NOT NULL,
    role VARCHAR2(50 CHAR) NOT NULL,
    theatre_id NUMBER(19,0)
);

CREATE TABLE city (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255 CHAR) NOT NULL,
    CONSTRAINT uk_city_name UNIQUE (name)
);

CREATE TABLE theatres (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255 CHAR) NOT NULL,
    city VARCHAR2(255 CHAR) NOT NULL,
    address VARCHAR2(255 CHAR) NOT NULL
);

CREATE TABLE screens (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    screen_name VARCHAR2(255 CHAR) NOT NULL,
    theatre_id NUMBER(19,0) NOT NULL,
    CONSTRAINT fk_screens_theatre FOREIGN KEY (theatre_id) REFERENCES theatres (id)
);

CREATE TABLE seats (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seat_number NUMBER(19,0) NOT NULL,
    seat_type VARCHAR2(255 CHAR) NOT NULL,
    active NUMBER(1,0) DEFAULT 1 NOT NULL,
    screen_id NUMBER(19,0) NOT NULL,
    CONSTRAINT fk_seats_screen FOREIGN KEY (screen_id) REFERENCES screens (id)
);

CREATE TABLE movies (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(255 CHAR) NOT NULL,
    description VARCHAR2(255 CHAR),
    language VARCHAR2(255 CHAR),
    duration NUMBER(10,0),
    genre VARCHAR2(255 CHAR),
    rating NUMBER(10,0),
    active NUMBER(1,0) DEFAULT 1 NOT NULL
);

CREATE TABLE shows (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movie_id NUMBER(19,0) NOT NULL,
    screen_id NUMBER(19,0) NOT NULL,
    start_time TIMESTAMP(6),
    end_time TIMESTAMP(6),
    price NUMBER(19,2),
    CONSTRAINT fk_shows_movie FOREIGN KEY (movie_id) REFERENCES movies (id),
    CONSTRAINT fk_shows_screen FOREIGN KEY (screen_id) REFERENCES screens (id)
);

CREATE TABLE show_seat (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    show_id NUMBER(19,0),
    seat_id NUMBER(19,0),
    status VARCHAR2(50 CHAR),
    CONSTRAINT fk_show_seat_show FOREIGN KEY (show_id) REFERENCES shows (id),
    CONSTRAINT fk_show_seat_seat FOREIGN KEY (seat_id) REFERENCES seats (id)
);

CREATE TABLE booking (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER(19,0),
    show_id NUMBER(19,0),
    status VARCHAR2(50 CHAR),
    payment_status VARCHAR2(50 CHAR),
    lock_expiry_time TIMESTAMP(6),
    CONSTRAINT fk_booking_show FOREIGN KEY (show_id) REFERENCES shows (id)
);

CREATE TABLE booking_show_seats (
    booking_id NUMBER(19,0) NOT NULL,
    show_seats_id NUMBER(19,0) NOT NULL,
    CONSTRAINT fk_booking_show_seats_booking FOREIGN KEY (booking_id) REFERENCES booking (id),
    CONSTRAINT fk_booking_show_seats_show_seat FOREIGN KEY (show_seats_id) REFERENCES show_seat (id)
);

CREATE INDEX idx_screens_theatre_id ON screens (theatre_id);
CREATE INDEX idx_seats_screen_id ON seats (screen_id);
CREATE INDEX idx_shows_movie_id ON shows (movie_id);
CREATE INDEX idx_shows_screen_id ON shows (screen_id);
CREATE INDEX idx_show_seat_show_id ON show_seat (show_id);
CREATE INDEX idx_show_seat_seat_id ON show_seat (seat_id);
CREATE INDEX idx_booking_show_id ON booking (show_id);
CREATE INDEX idx_booking_show_seats_booking_id ON booking_show_seats (booking_id);
CREATE INDEX idx_booking_show_seats_show_seats_id ON booking_show_seats (show_seats_id);
